; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.38"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[backup_migrate][version] = "3.1"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.16"

projects[features][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[icompany_config][download][type] = ""
;projects[icompany_config][download][url] = ""
;projects[icompany_config][type] = "module"
;projects[icompany_config][version] = "1.0"

projects[imce][version] = "1.9"

projects[jcarousel][version] = "2.6"

projects[jquery_update][version] = "2.3"

projects[link][version] = "1.3"

projects[menu_block][version] = "2.6"

projects[module_filter][version] = "2.0"

projects[multiblock][version] = "1.2"

projects[nodequeue][version] = "2.0-beta1"

projects[superfish][version] = "1.9"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

projects[webform][version] = "4.9"

projects[xmlsitemap][version] = "2.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[helloworld][destination] = "modules/custom"
projects[helloworld][download][type] = "git"
projects[helloworld][type] = "module"
projects[helloworld][download][url] = "https://github.com/spadgett16/Strateratech_aegir.git"


; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[icompany_module][download][type] = ""
;projects[icompany_module][download][url] = ""
;projects[icompany_module][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[icompany][download][type] = ""
;projects[icompany][download][url] = ""
;projects[icompany][type] = "theme"

; Libraries
libraries[superfish][directory_name] = superfish
libraries[superfish][download][type] = get
libraries[superfish][download][url] = https://github.com/mehrpadin/Superfish-for-Drupal/archive/1.x.zip


